version: "3.3"
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    restart: always
    ports:
      - "3307:3306"
  redis:
    image: redis
    command: redis-server
    ports:
      - "6379:6379"
